### ISSUE TITLE
分享一个自用的Rime皮肤

### ISSUE THREAD

**Issue by y1feng200156** [y1feng200156/issue-blog#3]
## 预览
![SCR-20220307-fn2](https://user-images.githubusercontent.com/1840653/156961849-4c2e4fb5-ddfb-49f8-8afe-a87d67b50c84.png)

## 配置

```yaml
name: "ubuntu"
font_face: "PingFangSC-Regular"
font_point: 14
label_font_face: "PingFangSC-Regular"
label_font_point: 12
comment_font_point: 14
candidate_list_layout: stacked
text_orientation: horizontal
candidate_format: "%c\u2005%@"
inline_preedit: true　
translucency: true
corner_radius: 3.0
base_offset: 3.0
alpha: 0.96
color_space: display_p3
back_color: 0x322B31
candidate_text_color: 0xD8FFFFFF
comment_text_color: 0x3FFFFFFF
label_color: 0xE5BAB8BA
hilited_candidate_back_color: 0x50234F
hilited_candidate_text_color: 0xD8FFFFFF
hilited_comment_text_color: 0x58FFFFFF
hilited_candidate_label_color: 0xE5C4B5C4
text_color: 0x3FFFFFFF
hilited_text_color: 0xD8FFFFFF
```
